var classes = [
    {
        "name": "Planck\\Pattern\\Compositor",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "inject",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Planck\\Pattern\\Decorator"
        ],
        "parents": [
            "Planck\\Pattern\\Decorator"
        ],
        "lcom": 1,
        "length": 14,
        "vocabulary": 7,
        "volume": 39.3,
        "difficulty": 6,
        "effort": 235.82,
        "level": 0.17,
        "bugs": 0.01,
        "time": 13,
        "intelligentContent": 6.55,
        "number_operators": 5,
        "number_operands": 9,
        "number_operators_unique": 4,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 63.57,
        "mIwoC": 63.57,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Planck\\Pattern\\",
        "pageRank": 0.5,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Pattern\\Traits\\Decorator",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "decorate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDecoratedObject",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__call",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Planck\\Exception"
        ],
        "parents": [],
        "lcom": 1,
        "length": 41,
        "vocabulary": 15,
        "volume": 160.18,
        "difficulty": 7,
        "effort": 1121.28,
        "level": 0.14,
        "bugs": 0.05,
        "time": 62,
        "intelligentContent": 22.88,
        "number_operators": 13,
        "number_operands": 28,
        "number_operators_unique": 5,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 29,
        "lloc": 29,
        "mi": 52.12,
        "mIwoC": 52.12,
        "commentWeight": 0,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 12,
        "totalSystemComplexity": 12,
        "package": "Planck\\Pattern\\Traits\\",
        "pageRank": 0.5,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]